linters:
  enable-all: true
  disable:
    - gci
    - tagliatelle
    - tagalign
    - gofumpt
    - depguard
    - exhaustruct
    - godox
    - godot
    - varnamelen
    - execinquery
    - gomnd
    - ireturn

issues:
  exclude-rules:
    - path: '(.+)mock_test\.go'
      linters:
        - gochecknoglobals

linters-settings:
  funlen:
    ignore-comments: true
    lines: 100
  lll:
    line-length: 200