name: release

on:
  push:
    tags:
      - 'publish-manager-v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.5'
      id: go

    - name: Build
      run: go build -o publish_manager_service.exe cmd/publish_manager_service/main.go

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        files: publish_manager_service.exe
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First release
          - Second release
