name: create ubuntu artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04.1

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.5'
      id: go

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -o publish_manager_service -ldflags "-X main.APIKey=${{ secrets.GEMINI_TOKEN }}" cmd/publish_manager_service/main.go

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish_manager_service-${{ github.sha}}
        path: publish_manager_service